### ISSUE TITLE
Deplay options for observer.

### ISSUE THREAD

**Issue by suyu34** [mobxjs/mobx-react-lite#149]
Is there any way to avoid render twice? Code like this https://codesandbox.io/s/0y0jjn56xw. Just like the `delay` options like`autorun`  in mobx.

**Comment by FredyC** [comment]
Well, it has nothing to do with this lib, it's purely MobX related question. Double re-render happens because you are updating the `x` twice. Do that 10 times and you get 10 re-renders ;) You need to enclose that in action (which does transaction), eg...

```js
class A {
  @observable.ref
  n = 0

  @action
  inc(count = 1) {
    this.n += count
  }

  constructor() {
    setTimeout(() => {
      this.inc(2)
    }, 3000)
  }
}
```

Also, friendly warning, don't even use `useMemo` for the state, you might randomly lose it, the `useRef` or `useState` are better candidates.

And if you want to make your life easier, forget about class-way of defining observables, we have fresh new utils available for that, [check the example](https://codesandbox.io/s/qx99jn2m09).

**Comment by suyu34** [comment]
oh thanks.
