### ISSUE TITLE
runInAction is necessary in LocalStore's (action) methods

### ISSUE THREAD

**Issue by asfernandes** [mobxjs/mobx-react-lite#170]
I'm following https://mobx-react.netlify.com/state-local and adapting a existing mobx-react app to use mobx-react-lite.

In this page it says:

> All properties of the returned object will be made observable automatically, getters will be turned into computed properties, and methods will be bound to the store and apply mobx transactions automatically. If new class instances are returned from the initializer, they will be kept as is.

My app uses mobx in strict mode.

I created a simple LocalStore with:

```ts
	const inputStore = useLocalStore(() => ({
		value: 'test',

		setValue(value: string) {
			this.value = value;
		}
	}));
```

But my `setValue` need to use `runInAction`, otherwise I have a strict-mode error.

I understand from the documentation that `runInAction` would not be necessary, as it says it run methods in mobx transactions.

**Comment by FredyC** [comment]
@mweststrate did this part and I don't yet fully understand it yet, so best if he can bring some light here.

Relevant PR: #139

**Comment by asfernandes** [comment]
If I understand the PR correctly, the change was intentional and explicity action would then be necessary?

Is it recommended or not to use mobx in strict-mode currently?

**Comment by mweststrate** [comment]
Actions in Mobx do 3 things:

1. wrap updates in transactions
2. allow modifications (if in strict mode)
3. disable tracking (so that they can be called from e.g. autorun without side effect

Because we cannot determine whether a method in a local store is used as an 'action' or as a 'view', we don't automatically convert them to actions (as 3. makes it unusable as view). However, since we can achieve 1. without any downsides, that is the only thing that is applied to all store methods automatically (+ binding). 

So if you need to use them in strict mode, you will need to be explicit about actions, `inc: action(function() { this.counter ++ })` (note that you can't combine arrow functions with `this`!). 
Alternatively, or actually the best practice; put `action` around the event handlers  that invoke the store methods instead.

**Comment by asfernandes** [comment]
@mweststrate I didn't read any of mobx-react-lite code, but wouldn't it be possible to have the "wrapped" methods in a level above the original ones (using proxy or another way)? In this way, internally called methods (when get calls a method) will call the original method, but external calls will call the wrapped action.

**Comment by mweststrate** [comment]
No, it could also be an externally called view, the get was just an example
to demonstrate the problem.

Op vr 31 mei 2019 21:24 schreef Adriano dos Santos Fernandes <
notifications@github.com>:

**Comment by FredyC** [comment]
I think we will include some DEV warning when strict mode is used (I hope it's possible to detect that) with a link to docs explaining how to deal with it.

**Comment by mweststrate** [comment]
I don't think there is a point in warning, as it could be false negatives

Op vr 31 mei 2019 22:36 schreef Daniel K. <notifications@github.com>:

**Comment by FredyC** [comment]
Hm, so you mean just document it and hope people don't get burned by it too often? :) I guess it's good enough step for now and if more people come struggling with it, we may consider something else. Closing for now.

**Comment by johnrichter** [comment]
👋 I'm starting to learn and use hooks and am starting to introduce the new mobx-react(-lite) hooks in my existing app as I develop (I use Mobx/classes everywhere already). I'm pretty excited, but just got burned by this and thought I'd share. I spent most of the day trying to figure out what was going on. 

It was throwing 

```
Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: ObservableObject@72.toggleCollapse
```

during the call to `useLocalStore()`. I spent a bit reading this thread and adding actions to the methods that modified observables (and trying to wrap everything with `action()` or `runInAction()` after I went a crazy). I eventually realized that the error was telling me that the store itself was being modified during initialization:

1. https://github.com/mobxjs/mobx-react-lite/blob/master/src/useLocalStore.ts#L19
2. https://github.com/mobxjs/mobx-react-lite/blob/master/src/useAsObservableSource.ts#L27 (when using an initial source)

I run Mobx with `enforceActions` set to `always` and once I switched it to `observed` the problem was fixed. I'm not sure if I want to keep it this way as enforcing actions can eliminate a class of human errors that I am (and others less familiar with Mobx) bound to make even if they make code a bit more verbose. I made a [sandbox](https://codesandbox.io/s/mobxreactlite-uselocalstore-strictmode-r9rhw) while troubleshooting.

From a developer experience standpoint I'd expect that these hooks would handle enforced actions without any knowledge of the internals. Would it make sense to wrap these assignments in an `action` internally?

```ts
function useLocalStore(initializer, current) {
    var source = useAsObservableSourceInternal(current, true);
    return React.useState(function () {
        var local = observable(initializer(source));
        if (isPlainObject(local)) {
            runInAction(() => {   
                Object.keys(local).forEach(function (key) {
                    var value = local[key];
                    if (typeof value === "function") {
                        local[key] = wrapInTransaction(value, local);
                    }
                });
            });
        }
        return local;
    })[0];
}
```

```ts
function useAsObservableSourceInternal() {
    ...
    runInAction(() => { Object.assign(res, current); });
    ...
}
```

I was able to modify the functions in `node_modules` and it worked just fine in `always` mode. As far as I understand hooks one couldn't the following because hooks must be at the top level, not nested within callbacks and other blocks.

```ts
let store = null;
runInAction(() => {
    store = useLocalStore(() => { ... });
});
if (store) { /* do stuff */ }
```

Is `enforceActions: 'always'` a requirement of mobx-react-lite? If not I'd be in favor of a more explicit warning. In either case I think more documentation is needed around strict mode. I'm up for submitting a PR if this is something that people would find useful 👍

**Comment by FredyC** [comment]
Thanks for detailed feedback and sorry for the frustrating experience. Frankly, we haven't been paying much attention to strict mode yet so it's great you bring it up. The PR you have made seems to be working correctly, but I will leave it to cook for a couple of days if someone else wants to chime in.

cc @xaviergonz @urugator

**Comment by urugator** [comment]
Original behavior of strict mode is equal to current `observed`. It allows to mutate observables during initialization (when they're not observed yet) - like in this case or inside constructors/computed etc.
The primary goal of `action` is to batch reactions (observers). If there are no reactions, there is nothing to batch, therefore a missing `action` is not a big deal.
The `always` is "super strict" and throws always, so a missing `action` can be sometimes detected a bit sooner, but it can also complicate init logic.

The PR looks good.

**Comment by johnrichter** [comment]
Thanks for the clarification! I've probably been too focused on building my app to really think about the difference before. `observed` does make a lot of practical sense over `always`. I have a bunch of init ugly init code that looks like the following:

```ts
@observer
class MyComponent extends React.Component<MyProps> {
    // Have to non-nullify the declaration because its not initialized in the constructor 
    // and I can't assign directly because of `enforceActions: always`
    @observable private _myObservableFlag!: IObservableValue<boolean>;

    constructor(props: MyProps) {
        super(props);
        // Must run initialization in an action
        runInAction('Initialize state', () => {
            this._myObservableFlag = observable.box(false);
        });
    }
}
```

My goal is to leverage typing and strict modes as much as I can for stability, consistency, and human error protection. I think it's probably time for me to and relax this approach a bit for Mobx and just assign directly for unobserved state. Gotta love over thinking.

**Comment by johnrichter** [comment]
I ran into another issue this morning that I feel like I should have ran into or realized yesterday. `observed` mode works fine on the initial render, but any subsequent renders will trigger the same issue. Reverting to `never` fixes the problem. I made a [sandbox](https://codesandbox.io/s/mobxreactlite-uselocalstore-strictmode-rerender-jz99e) to show this. Just resize the preview browser window.

**Comment by FredyC** [comment]
@johnrichter But in that sandbox, you don't have the fix you made in #172, so technically it behaves correctly?

**Comment by urugator** [comment]
That's the `Object.assign(res, current);`, which is actually intened to notify observers.
In this case the strict mode correctly revealed actual bug.

**Comment by johnrichter** [comment]
@FredyC That is correct.

**Comment by FredyC** [comment]
Published in 1.4.1

**Comment by FredyC** [comment]
> I couldn't find a tag or release in `mobx-react-lite` to match the release on npm. Would it be possible to do that as well?

I am not sure what you mean by that.

**Comment by FredyC** [comment]
You are right, I must have missed that because of the hasty release. Fixed now.

**Comment by NRamirezCR** [comment]
About this statement:

> Alternatively, or actually the best practice; put `action` around the event handlers that invoke the store methods instead.

I'm probably missing something related to the way MobX works, but for me it makes more sense to wrap it around the store method. Why is it claimed that the best practice is to put the `action` around the event handlers instead of in the store method directly?

**Comment by mweststrate** [comment]
Because onClick = ()=> { store.a(); store.b() } will be two batches hence
two times propagating changes without an outer 'action'

Op ma 16 sep. 2019 20:29 schreef Norman Ramírez <notifications@github.com>:
