### ISSUE TITLE
useObserver won't re-render when store array changes.

### ISSUE THREAD

**Issue by Suedo** [mobxjs/mobx-react-lite#261]
I am trying to create a simple todo list kinda app, where I will type a name of a city, and on clicking an add button, it will update the list of the cities in the UI with the newly added city. But the UI isn't getting updated, and it seems to me like `useObserver` isn't re-rendering.

Codesandbox [here](https://codesandbox.io/s/ts-react-mob-hooks-qj0fe?fontsize=14&hidenavigation=1&theme=dark)

Can someone please tell me how to fix this :(

**Comment by FredyC** [comment]
Fixed version: https://codesandbox.io/s/ts-react-mob-hooks-yge9b

Related issue/comment: https://github.com/mobxjs/mobx-react-lite/issues/174#issuecomment-503909270

**Comment by Suedo** [comment]
You edited the store, and added the `slice()` method to the array in `CitiesList `part of `city.tsx`. 

Thank you so much for your help! I tried to follow comment #174 but didn't understand much. 

If it's not too much trouble, can you please let me know what `slice()` contributes here?

**Comment by mweststrate** [comment]
Did you read https://mobx.js.org/best/react? Make sure to read that one
first, it probably will answer your question :)

**Comment by FredyC** [comment]
@Suedo Well, `slice` is one way to "clone" the array. MobX won't be able to track whole array changes unless you have some iteration over those. The linked page by Michel does not really explain this. I don't think we have a good explanation for that but it's a very repeated question :-|

**Comment by mweststrate** [comment]
Just checked, the example isn't rendering because you should have used
.slice(), but, because the CityView isn't marked as `observer`. Wrapping
that one in `observer` will fix the issue. The `slice()` is only needed
when you need to pass data to third party components that are not MobX
aware so you need unmobxify the data (just as you would call .toJS with
e.g. immutable.js. However in your case, it is just as matter of not having
made the CityView component MobX enabled.

**Comment by mks11** [comment]
I am wondering if you have an explanation for a derivative code from the "recipe" section of documentation. https://mobx-react.js.org/recipes-migration  The part talks about omitting `observer` from the component when you follow the following pattern. My question is when I have an array, I loose the reactivity when I omit the `observer` otherwise it's fine. For instance, imagine having an extra property like `items` array returned by the function from useObserver, and in the store pushing something into it. Thanks a lot.

```
// use mobx-react@6.1.2 or  mobx-react-lite
import { useObserver } from 'mobx-react' 
function useUserData() { \n
  const { user, order } = useStores()
  return useObserver(() => ({
    username: user.name,
    orderId: order.id,
  }))
}


const UserOrderInfo = () => {
  // this works now just fine
  const { username, orderId } = useUserData()
  return (
    <div>
      {username} has order {orderId}
    </div>
  )
}
```

**Comment by FredyC** [comment]
@mks11 Please open a new issue with reproduction.

**Comment by mks11** [comment]
@FredyC  thanks. I have a quick question .. 
does useObserver(()=>({
    ...
})) like above is reactive for observable objects? I have an object object that i return from useObserver() where the problem happens.

**Comment by FredyC** [comment]
Sorry, but if you have unrelated questions, these are better asked in separate issue with appropriate details.
