### ISSUE TITLE
Create-react-app & mobx-react-lite

### ISSUE THREAD

**Issue by SimonVanherweghe** [mobxjs/mobx-react-lite#266]
Since a couple of days, when you create a new create-react-app project, it comes with `<React.StrictMode>` as default.

Took me a while to find out why my observable wasn't working. mobx-react-lite@next fixes this, but I found this almost by accident. I don't know if this is something to address in the documentation? Or should this rase an error/warning?

Codesandbox example to demonstrate: https://codesandbox.io/s/reactstrictmode-mobx-react-lite-7kndk

**Comment by FredyC** [comment]
Hah, that's funny they added something like that as a meager "enhancement" in patch version. It's just part of the template so it won't affect existing apps, but still, it's kinda weird.

The existence of `next` is mentioned [in readme](https://github.com/mobxjs/mobx-react-lite#react-strict-mode-). It's not part of the official docs because it's still experimental and we never got enough feedback if it works correctly. It tries to overcome the issue in a slightly hackish way.

Furthermore, with Concurrent mode getting slowly finalized, we wanted to make sure it works correctly with it too before cutting the next major version. But it never happened because testing tools are not ready to use Concurrent mode either.

Perhaps it might be ultimately better to go with 2.0 sooner to solve the Strict mode only and focus on Concurrent mode as part of 3.0 if necessary.

**Comment by mweststrate** [comment]
I think that is a good idea, I suspect that the validation will never gonna
happen without an explicit release, and even after release we can still fix
things ;)

**Comment by FredyC** [comment]
2.0.1 published, use it for the official StrictMode support.
