### ISSUE TITLE
Incompatibility with Next.js 8

### ISSUE THREAD

**Issue by programbo** [mobxjs/mobx-react-lite#71]
I am cross-posting this issue in the hope that someone here will know what is stopping mobx-react-lite from working with Next.js 8.

Original issue 👉 https://github.com/zeit/next.js/issues/6490

Failing Next.js example 👉 https://codesandbox.io/s/m4l10j80vx

Working CRA example 👉 https://codesandbox.io/s/53m7j6y9wx

**Comment by FredyC** [comment]
That is indeed very strange. I am not familiar with Next.js at all. It seems to me it does not like global variables? :)

Made your example working be utilizing `useObservable` instead of class-based global store. Perhaps try to add that store instance into React Context or something, but apparently, globals are bad in Next for some reason.

https://codesandbox.io/s/6vnnkw9k5n

**Comment by programbo** [comment]
Cool! I initially used React Context but then inlined the store to simplify the demo and remove points of failure. I love that the solution is **USE MORE HOOKS**! :D

**Comment by FredyC** [comment]
Alright, closing then, have fun :)

**Comment by FredyC** [comment]
And just to note, the `useObservable` is not a full replacement for a class-based solution as it does not support computed and actions. I would recommend [mobx-state-tree](https://github.com/mobxjs/mobx-state-tree) for a more complex states.
